E_commerce_store/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from core import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', views.HomeView.as_view(), name='home'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('cart/', include('cart.urls', namespace='cart')),
    path('staff/', include('staff.urls', namespace='staff')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from .views import (
    ProductListView,
    ProductDetailView,
    CartView,
    IncreaseQuantityView,
    DecreaseQuantityView,
    DeleteItemView,
    CheckoutView,
    PaymentView,
    ThankYouView,
    ConfirmOrderView,
    OrderDetailView,
)

app_name = 'cart'
urlpatterns = (
    path('', CartView.as_view(), name='summary'),
    path('shop/', ProductListView.as_view(), name='product_list'),
    path('shop/<slug>/', ProductDetailView.as_view(), name='product_detail'),
    path('increase-quantity/<pk>/', IncreaseQuantityView.as_view(), name='increase_quantity'),
    path('decrease-quantity/<pk>/', DecreaseQuantityView.as_view(), name='decrease_quantity'),
    path('delete-item/<pk>/', DeleteItemView.as_view(), name='delete_item'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('payment/', PaymentView.as_view(), name='payment'),
    path('thanks/', ThankYouView.as_view(), name='thank-you'),
    path('confirm-order/', ConfirmOrderView.as_view(), name='confirm-order'),
    path('orders/<pk>/', OrderDetailView.as_view(), name='order-detail'),
)

cart/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.db.models.signals import pre_save
from django.utils.text import slugify
from django.shortcuts import reverse

User = get_user_model()


class PriceVariables(models.Model):
    tax = models.FloatField(default=0)
    discount = models.FloatField(default=0)
    delivery = models.IntegerField(default=0)

    def __str__(self):
        return f"Tax: {self.tax}, Discount: {self.discount}, Delivery: {self.delivery}"

    def get_tax(self):

        return self.tax

    def get_discount(self):
        return self.discount

    def get_delivery(self):
        return self.delivery


class Address(models.Model):
    ADDRESS_CHOICES = (
        ('B', 'Billing'),
        ('S', 'Shipping'),
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    address_line1 = models.CharField(max_length=150)
    address_line2 = models.CharField(max_length=150)
    city = models.CharField(max_length=100)
    zip_code = models.CharField(max_length=20)
    address_type = models.CharField(max_length=1, choices=ADDRESS_CHOICES)
    default = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.address_line1}, {self.address_line2}, {self.city}, {self.zip_code}"

    class Meta:
        verbose_name_plural = 'Addresses'


class FormatVariation(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Product(models.Model):
    title = models.CharField(max_length=150)
    slug = models.SlugField(unique=True)
    image = models.ImageField(upload_to='product_images')
    description = models.TextField()
    price = models.IntegerField(default=0)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=False)
    available_formats = models.ManyToManyField(FormatVariation)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("cart:product_detail", kwargs={'slug': self.slug})

    def get_price(self):
        # $10 => $10.00, Stripe tar priset i cent
        return f"{self.price/100:.2f}"


class OrderItem(models.Model):
    order = models.ForeignKey("Order", related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    format = models.ForeignKey(FormatVariation, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.quantity} * {self.product.title}"

    def get_raw_total_item_price(self):
        return self.quantity * self.product.price

    def get_total_item_price(self):
        return f"{self.get_raw_total_item_price()/100:.2f}"


class Order(models.Model):
    user = models.ForeignKey(User, blank=True, null=True, on_delete=models.CASCADE)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField(blank=True, null=True)
    ordered = models.BooleanField(default=False)
    billing_address = models.ForeignKey(Address, related_name='billing_address', blank=True, null=True, on_delete=models.SET_NULL)
    shipping_address = models.ForeignKey(Address, related_name='shipping_address', blank=True, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return self.reference_number

    @property
    def reference_number(self):
        return f"ORDER-{self.pk}"

    def get_raw_subtotal(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_raw_total_item_price()
        return total

    def get_subtotal(self):
        return f"{self.get_raw_subtotal()/100:.2f}"

    def get_raw_total(self):
        subtotal = self.get_raw_subtotal()
        t = PriceVariables.objects.first()

        total = subtotal*(1-t.get_discount())*(1+t.get_tax()) + t.get_delivery()
        return total

    def get_total(self):
        return f"{self.get_raw_total()/100:.2f}"


class Payment(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='payments')
    payment_method = models.CharField(max_length=20, choices=(
        ('PayPal', 'PayPal'),
    ))
    timestamp = models.DateTimeField(auto_now_add=True)
    successful = models.BooleanField(default=False)
    amount = models.FloatField()
    raw_response = models.TextField()

    def __str__(self):
        return self.reference_number

    @property
    def reference_number(self):
        return f"PAYMENT-{self.order}-{self.pk}"


def pre_save_product_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = slugify(instance.title)


pre_save.connect(pre_save_product_receiver, sender=Product)

cart/forms.py
from django.contrib.auth import get_user_model
from django import forms
from .models import OrderItem, FormatVariation, Product, Address

User = get_user_model()


class AddToCartForm(forms.ModelForm):
    format = forms.ModelChoiceField(queryset=FormatVariation.objects.none())

    class Meta:
        model = OrderItem
        fields = ['quantity', 'format']

    def __init__(self, *args, **kwargs):
        product_id = kwargs.pop('product_id')
        product = Product.objects.get(id=product_id)
        super().__init__(*args, **kwargs)

        self.fields['format'].queryset = product.available_formats.all()


class AddressForm(forms.Form):
    shipping_address_line1 = forms.CharField(required=False)
    shipping_address_line2 = forms.CharField(required=False)
    shipping_zip_code = forms.CharField(required=False)
    shipping_city = forms.CharField(required=False)

    billing_address_line1 = forms.CharField(required=False)
    billing_address_line2 = forms.CharField(required=False)
    billing_zip_code = forms.CharField(required=False)
    billing_city = forms.CharField(required=False)

    selected_shipping_address = forms.ModelChoiceField(
        Address.objects.none(), required=False
    )
    selected_billing_address = forms.ModelChoiceField(
        Address.objects.none(), required=False
    )

    def __init__(self, *args, **kwargs):
        user_id = kwargs.pop('user_id')
        super().__init__(*args, **kwargs)

        user = User.objects.get(id=user_id)

        shipping_address_qs = Address.objects.filter(
            user=user,
            address_type='S'
        )
        billing_address_qs = Address.objects.filter(
            user=user,
            address_type='B'
        )

        self.fields['selected_shipping_address'].queryset = shipping_address_qs
        self.fields['selected_billing_address'].queryset = billing_address_qs

    def clean(self):
        data = self.cleaned_data

        selected_shipping_address = data.get('selected_shipping_address', None)
        if selected_shipping_address is None:
            if not data.get('shipping_address_line1', None):
                self.add_error("shipping_address_line1", "Please fill in this field.")
            if not data.get('shipping_address_line2', None):
                self.add_error("shipping_address_line2", "Please fill in this field.")
            if not data.get('shipping_zip_code', None):
                self.add_error("shipping_zip_code", "Please fill in this field.")
            if not data.get('shipping_city', None):
                self.add_error("shipping_city", "Please fill in this field.")

        selected_billing_address = data.get('selected_billing_address', None)
        if selected_billing_address is None:
            if not data.get('billing_address_line1', None):
                self.add_error("billing_address_line1", "Please fill in this field.")
            if not data.get('billing_address_line2', None):
                self.add_error("billing_address_line2", "Please fill in this field.")
            if not data.get('billing_zip_code', None):
                self.add_error("billing_zip_code", "Please fill in this field.")
            if not data.get('billing_city', None):
                self.add_error("billing_city", "Please fill in this field.")

cart/views.py
import datetime
import json
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.views import generic
from django.shortcuts import get_object_or_404, reverse, redirect
from .forms import AddToCartForm, AddressForm
from .models import Product, OrderItem, PriceVariables, Address, Payment, Order
from .utils import get_or_set_order_session


class ProductListView(generic.ListView):
    template_name = 'cart/product_list.html'

    def get_queryset(self):
        queryset = Product.objects.all()
        return queryset


class ProductDetailView(generic.FormView):
    template_name = 'cart/product_detail.html'
    form_class = AddToCartForm

    def get_object(self):
        return get_object_or_404(Product, slug=self.kwargs["slug"])

    def get_success_url(self):
        return reverse("cart:summary")

    def get_form_kwargs(self):
        kwargs = super(ProductDetailView, self).get_form_kwargs()
        kwargs['product_id'] = self.get_object().id
        return kwargs

    def form_valid(self, form):
        order = get_or_set_order_session(self.request)
        product = self.get_object()

        item_filter = order.items.filter(
            product=product,
            format=form.cleaned_data['format'],
        )
        if item_filter.exists():
            item = item_filter.first()
            item.quantity = int(form.cleaned_data['quantity'])
            item.save()

        else:
            new_item = form.save(commit=False)
            new_item.product = product
            new_item.order = order
            new_item.save()

        return super(ProductDetailView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(ProductDetailView, self).get_context_data(**kwargs)
        context['product'] = self.get_object()
        return context


class CartView(generic.TemplateView):
    template_name = 'cart/cart.html'

    def get_context_data(self, **kwargs):
        context = super(CartView, self).get_context_data(**kwargs)
        context['order'] = get_or_set_order_session(self.request)
        price_vars = PriceVariables.objects.first()
        raw_discount = (price_vars.discount * context['order'].get_raw_subtotal())
        context['tax'] = (price_vars.tax*(context['order'].get_raw_subtotal()-raw_discount))/100
        context['delivery'] = price_vars.delivery / 100
        context['discount'] = raw_discount / 100

        return context


class IncreaseQuantityView(generic.View):

    def get(self, request, *args, **kwargs):
        order_item = get_object_or_404(OrderItem, id=kwargs['pk'])
        order_item.quantity += 1
        order_item.save()
        return redirect("cart:summary")


class DecreaseQuantityView(generic.View):

    def get(self, request, *args, **kwargs):
        order_item = get_object_or_404(OrderItem, id=kwargs['pk'])
        if order_item.quantity <= 1:
            order_item.delete()
        else:
            order_item.quantity -= 1
            order_item.save()

        return redirect("cart:summary")


class DeleteItemView(generic.View):

    def get(self, request, *args, **kwargs):
        order_item = get_object_or_404(OrderItem, id=kwargs['pk'])
        order_item.delete()

        return redirect("cart:summary")


class CheckoutView(generic.FormView):
    template_name = "cart/checkout.html"
    form_class = AddressForm

    def get_success_url(self):
        return reverse("cart:payment")

    def form_valid(self, form):
        order = get_or_set_order_session(self.request)
        selected_shipping_address = form.cleaned_data.get('selected_shipping_address')
        selected_billing_address = form.cleaned_data.get('selected_billing_address')

        if selected_shipping_address:
            order.shipping_address = selected_shipping_address
        else:
            address = Address.objects.create(
                address_type='S',
                user=self.request.user,
                address_line1=form.cleaned_data['shipping_address_line1'],
                address_line2=form.cleaned_data['shipping_address_line2'],
                zip_code=form.cleaned_data['shipping_zip_code'],
                city=form.cleaned_data['shipping_city'],
            )
            order.shipping_address = address

        if selected_billing_address:
            order.billing_address = selected_billing_address
        else:
            address = Address.objects.create(
                address_type='B',
                user=self.request.user,
                address_line1=form.cleaned_data['billing_address_line1'],
                address_line2=form.cleaned_data['billing_address_line2'],
                zip_code=form.cleaned_data['billing_zip_code'],
                city=form.cleaned_data['billing_city'],
            )
            order.billing_address = address
        order.save()
        messages.info(
            self.request, "You have successfully added your addresses")
        return super(CheckoutView, self).form_valid(form)

    def get_form_kwargs(self):
        kwargs = super(CheckoutView, self).get_form_kwargs()
        kwargs["user_id"] = self.request.user.id
        return kwargs

    def get_context_data(self, **kwargs):
        context = super(CheckoutView, self).get_context_data(**kwargs)
        context['order'] = get_or_set_order_session(self.request)
        price_vars = PriceVariables.objects.first()
        raw_discount = (price_vars.discount * context['order'].get_raw_subtotal())
        context['tax'] = (price_vars.tax*(context['order'].get_raw_subtotal()-raw_discount))/100
        context['delivery'] = price_vars.delivery / 100
        context['discount'] = raw_discount / 100

        return context


class PaymentView(generic.TemplateView):
    template_name = "cart/payment.html"

    def get_context_data(self, **kwargs):
        context = super(PaymentView, self).get_context_data(**kwargs)
        context["PAYPAL_CLIENT_ID"] = settings.PAYPAL_CLIENT_ID
        context['order'] = get_or_set_order_session(self.request)
        context['CALLBACK_URL'] = self.request.build_absolute_uri(reverse("cart:thank-you"))
        return context

class ConfirmOrderView(generic.View):
    def post(self, request, *args, **kwargs):
        order = get_or_set_order_session(request)
        body = json.loads(request.body)
        # print(body)
        payment = Payment.objects.create(
            order=order,
            successful=True,
            raw_response=json.dumps(body),
            amount=float(body["purchase_units"][0]["amount"]["value"]),
            payment_method='PayPal'
        )
        order.ordered = True
        order.ordered_date = datetime.date.today()
        order.save()
        return JsonResponse({"data": "Success"})


class ThankYouView(generic.TemplateView):
    template_name = "cart/thanks.html"


class OrderDetailView(LoginRequiredMixin, generic.DetailView):
    template_name = "order.html"
    queryset = Order.objects.all()
    context_object_name = 'order'


    def get_context_data(self, **kwargs):
        context = super(OrderDetailView, self).get_context_data(**kwargs)
        price_vars = PriceVariables.objects.first()
        raw_discount = (price_vars.discount * context['order'].get_raw_subtotal())
        context['tax'] = (price_vars.tax * (context['order'].get_raw_subtotal() - raw_discount)) / 100
        context['delivery'] = price_vars.delivery / 100
        context['discount'] = raw_discount / 100

        return context

templates/cart/cart.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="bg-light py-3">
    <div class="container">
        <div class="row">
            <div class="col-md-12 mb-0">
                <a href="{% url 'home' %}">Home</a>
                <span class="mx-2 mb-0">/</span>
                <strong class="text-black">Cart</strong>
            </div>
        </div>
    </div>
</div>

<div class="site-section">
    <div class="container">
        <div class="row-mb-5">
                <div class="col-md-12">
                    <div class="site-blocks-table">
                        <table>
                            <thead>
                                <tr>
                                    <th>Image</th>
                                    <th>Product</th>
                                    <th>Price</th>
                                    <th>Quantity</th>
                                    <th>Total</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for item in order.items.all %}
                                    <tr>
                                        <td class="product-thumbnail">
                                            <img src="{{ item.product.image.url }}" class="img-fluid">
                                        </td>
                                        <td class="product-name">
                                            <h2 class="h5 text-black">{{ item.product.title }}</h2>
                                            <small>Format: {{ item.format.name }}</small>
                                        </td>
                                        <td>
                                            ${{ item.product.get_price }}
                                        </td>
                                        <td>
                                            <div class="input-group mb-3" style="max-width: 120px;">
                                                <div class="input-group-prepend">
                                                    <a href="{% url 'cart:decrease_quantity' item.id %}" class="btn btn-outline-primary">
                                                        &minus;
                                                    </a>
                                                </div>
                                                <input type="text" class="form-control text-center" value="{{ item.quantity }}">
                                                <div class="input-group-append">
                                                    <a href="{% url 'cart:increase_quantity' item.id %}" class="btn btn-outline-primary">
                                                        &plus;
                                                    </a>
                                                </div>
                                            </div>
                                        </td>
                                        <td>
                                            ${{ item.get_total_item_price }}
                                        </td>
                                        <td>
                                            <a href="{% url 'cart:delete_item' item.id %}" class="btn btn-primary btn-sm">X</a>
                                        </td>
                                    </tr>
                                    {% empty %}
                                    <tr>
                                        <td colspan="6">
                                            There are no items in your cart. <a href="{% url 'cart:product_list' %}">Continue shopping</a>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
        </div>
        {%  if order.items.count > 0 %}
            <div class="row">
                <div class="col-md-6">
                    <div class="row mb-5">
                        <div class="col-md-12">
                            <a class="btn btn-outline-primary btn-sm btn-block" href="{% url 'cart:product_list' %}">Continue shopping</a>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 pl-5">
                    <div class="row justify-content-end">
                        <div class="col-md-12">
                            <div class="row">
                                <div class="col-md-12 text-right border-bottom mb-5">
                                    <h3 class="text-black h4 text-uppercase">Cart Totals</h3>
                                </div>
                            </div>

                            <div class="row mb-3">
                                <div class="col-md-6">
                                    <span class="text-black">Subtotal</span>
                                </div>
                                <div class="col-md-6 text-right">
                                    <strong class="text-black">${{ order.get_subtotal }}</strong>

                                </div>
                            </div>
                            <div class="row mb-3">
                                <div class="col-md-6">
                                    <span class="text-black">Discount</span>
                                </div>
                                <div class="col-md-6 text-right">
                                    <strong class="text-black">${{ discount }}</strong>

                                </div>
                            </div>
                            <div class="row mb-3">
                                <div class="col-md-6">
                                    <span class="text-black">Tax</span>
                                </div>
                                <div class="col-md-6 text-right">
                                    <strong class="text-black">${{ tax }}</strong>

                                </div>
                            </div>
                            <div class="row mb-3">
                                <div class="col-md-6">
                                    <span class="text-black">Delivery cost</span>
                                </div>
                                <div class="col-md-6 text-right">
                                    <strong class="text-black">${{ delivery }}</strong>

                                </div>
                            </div>
                            <div class="row mb-5">
                                <div class="col-md-6">
                                    <span class="text-black">Total</span>
                                </div>
                                <div class="col-md-6 text-right">
                                    <strong class="text-black">${{ order.get_total }}</strong>

                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <a class="btn btn-primary btn-lg py-3 btn-block" href="{% url 'cart:checkout' %}"> Proceed to checkout</a>
                                </div>
                            </div>


                        </div>
                    </div>
                </div>
            </div>
        {% endif %}
    </div>
</div>


{% endblock content %}

templates/cart/payment.html
{% extends "base.html" %}

{% block content %}

<style>

.lds-ring {
  display: inline-block;
  position: relative;
  width: 80px;
  height: 80px;
}
.lds-ring div {
  box-sizing: border-box;
  display: block;
  position: absolute;
  width: 64px;
  height: 64px;
  margin: 8px;
  border: 8px solid rgb(155, 81, 81);
  border-radius: 50%;
  animation: lds-ring 1.2s cubic-bezier(0.5, 0, 0.5, 1) infinite;
  border-color: rgb(155, 81, 81) transparent transparent transparent;
}
.lds-ring div:nth-child(1) {
  animation-delay: -0.45s;
}
.lds-ring div:nth-child(2) {
  animation-delay: -0.3s;
}
.lds-ring div:nth-child(3) {
  animation-delay: -0.15s;
}
@keyframes lds-ring {
  0% {
    transform: rotate(0deg);
  }
  100% {
    transform: rotate(360deg);
  }
}

</style>

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="alert alert-success" role="alert" id="alertSuccess" style="display:none;">
                Your payment was successful.
            </div>
            <div class="alert alert-danger" role="alert" id="alertFailure" style="display:none;">
                Your payment failed. Please try again.
            </div>
            <div class="text-center py-3">
            <div id="loader" class="lds-ring" style="margin: auto; display: none;">
                <div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div></div>
            </div>
            <div id="paymentInfo">
                <p>Order total: ${{ order.get_total }}</p>
                <h4>Select a payment method</h4>
                <div id="paypal-button-container"></div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block scripts %}
<script
    src="https://www.paypal.com/sdk/js?client-id={{ PAYPAL_CLIENT_ID }}">
</script>
<script>

    const loader = document.getElementById('loader');
    const paymentInfo = document.getElementById('paymentInfo');

    function toggleLoader(on) {
        loader.style.display = on === true ? "block" : "none";
        paymentInfo.style.display = on === true ? "none" : "block";
    }

    function getCookie(name) {
        let cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            const cookies = document.cookie.split(';');
            for (let i = 0; i < cookies.length; i++) {
                const cookie = cookies[i].trim();
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
    const csrftoken = getCookie('csrftoken');

    function sendOrderConfirmed(details) {
        return fetch("{% url 'cart:confirm-order' %}", {
            method: "post",
            body: JSON.stringify(details),
            headers: {
                "Content-Type": "application/json",
                "X-CSRFToken": csrftoken
            }
        })
    }

    paypal.Buttons({
        createOrder: function(data, actions) {
          // This function sets up the details of the transaction, including the amount and line item details.
          return actions.order.create({
            purchase_units: [{
              amount: {
                value: '{{ order.get_total }}'
              }
            }]
          });
        },
        onApprove: function(data, actions) {
            toggleLoader(true);
          // This function captures the funds from the transaction.
          return actions.order.capture().then(function(details) {
            // This function shows a transaction success message to your buyer.
              sendOrderConfirmed(details).then(res => {
                  toggleLoader(false)
                  const_alertSuccess = document.getElementById('alertSuccess');
                  alertSuccess.style.display = 'block';
                  setTimeout(function() {
                 window.location.replace("{{ CALLBACK_URL }}")
                }, 3000);
              })
          })
              .catch(err => {
                const_alertFailure = document.getElementById('alertFailure');
                alertFailure.style.display = 'block';
              })
              .finally(() => toggleLoader(false));
        }
      }).render('#paypal-button-container');
</script>

{% endblock scripts %}

templates/cart/product_detail.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

<div class="bg-light py-3">
    <div class="container">
        <div class="row">
            <div class="col-md-12 mb-0">
                <a href="{% url 'home' %}">Home</a>
                <span class="mx-2 mb-0">/</span>
                <strong class="text-black">{{ product.title }}</strong>
            </div>
        </div>
    </div>
</div>

<div class="site-section">
    <div class="container">
        <div class="row mb-5">
            <div class="col-md-6">
                <img src="{{ product.image.url }}" class="img-fluid" >
            </div>
            <div class="col-md-6">
                <h2 class="text-black">{{ product.title }}</h2>
                <p>{{ product.description }}</p>
                <hr>
                <p>Created: {{ product.created }}</p>
                <hr>
                <form method="POST">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type="submit" class="btn btn-sm btn-primary buy-now">Add to cart</button>
                </form>


            </div>
        </div>
    </div>
</div>


{% endblock content %}

templates/cart/thanks.html
{% extends 'base.html' %}

{% block content %}
    Thank you
{% endblock content %}